### PR TITLE
Updating configuration ui

### PR DESCRIPTION
**Pull request by jamesrichard91**
Updated the style of the config.

Created sections (server and proxy), sections are collapsible and expandable, replaced Atlassian progress spinner with FontAwesome, stopped using the atlassian styling for the form and reproduced it as close as I could so it should look the same regardless or product/version

### CODE REVIEW

**Comment by jrichardBD** [comment]
@ekerwin @stevebillings @akamen @psantos1113  Please review

**Comment by psantos1113** [comment]
looks good!

**Comment by stevebillings** [comment]
Looks good.

**Comment by ekerwin** [comment]
Oh my goodness...that is a ton to change for such a small thing! I hope it wasn't TOO painful! The changes, given that they are needed, seem fine to me.

**Pull request merged**
